### ISSUE TITLE
the link is expired

### ISSUE THREAD

**Issue by rederxz** [Gold-Sea/Chinese-poems-generation-based-on-pictures#1]
the link
https://disk.pku.edu.cn:443/link/A54728C8E322E8F1E3F59235F44BDF4A 
is expired.

**Comment by Gold-Sea** [comment]
https://disk.pku.edu.cn:443/link/4FC6F374928F6FA7D1F61425700F3B56
有效期限：2023-01-12 23:59

I am sorry, the pku disk is unstable.

**Comment by rederxz** [comment]
> https://disk.pku.edu.cn:443/link/4FC6F374928F6FA7D1F61425700F3B56
> 有效期限：2023-01-12 23:59
> 
> I am sorry, the pku disk is unstable.

thanks a lot!

**Comment by zhangbaijin** [comment]
老哥，连接失效了，方便再发一个嘛

**Comment by Gold-Sea** [comment]
> 
> 
> 老哥，连接失效了，方便再发一个嘛

https://disk.pku.edu.cn:443/link/FACCA1097CC5AFE97D85FF9E493F5D86

**Comment by zhangbaijin** [comment]
十分感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Gold-Sea/Chinese-poems-generation-based-on-pictures"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月19日(星期三) 晚上8:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Gold-Sea/Chinese-poems-generation-based-on-pictures] the link is expired (#1)





  
老哥，连接失效了，方便再发一个嘛
  
https://disk.pku.edu.cn:443/link/FACCA1097CC5AFE97D85FF9E493F5D86
